version: "3"

services:
  gogs:
    image: gogs/gogs
    deploy:
      restart_policy: 
        condition: on-failure
    networks:
      - dev
    ports:
      - 2222:22
      - 80:3000
    volumes:
      - '/srv/gogs:/data'
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.9.1
    deploy:
      restart_policy: 
        condition: on-failure
    networks:
      - dev
    ports:
      - 8081:8081
    volumes:
      - '/srv/artifactory:/var/opt/jfrog/artifactory'
  postgres:
    image: postgres
    deploy:
      restart_policy: 
        condition: on-failure
    networks:
      - dev
    environment:
      - POSTGRESQL_PASSWORD="${POSTGRESQL_PASSWORD}"
    volumes:
      - '/srv/postgres:/var/lib/postgresql/data'
  jenkins:
    image: jenkins-docker
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - dev
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - '/srv/jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  dev:
    external: true